---
title: "Ket qua bau cu Quoc Hoi khoa XIV"
author: "Mai Ng"
date: "June 11, 2016"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
```

```{r lib, include=FALSE}
library(dplyr)
library(knitr)
library(tidyr)
library(ggplot2)
library(readr)
library(pander)
library(DT)
library(xlsx)
```

```{r db, include=FALSE}
path <- 1 #1=mac #2=wins

if (path == 2) {
  work_link <- "C:/Users/Administrator/Dropbox/MAI/R/Election/election.csv"
}else{
  home_link <- "/Users/mainguyen/ownCloud/MAI/R/Election/election.csv"
}
ele <- read_csv(home_link)
```

## {.tabset}
###1. Summary Index
```{r summary, results='asis'}

#gender
ele$gender <- substr(ele$candidates, 1, 1)
ele$gender[ele$gender=="B"] <- "female"
ele$gender[ele$gender=="Ô"] <- "male" 

sumall <- length(ele$provinces)
sumfe <- length(ele$gender[ele$gender=="female"])
summa <- length(ele$gender[ele$gender=="male"]) 

tab0 <- data.frame(index=c("Number of candidates", "Number of female candidates", "Number of male candidates"), total=c(sumall, sumfe, summa))
names(tab0) <- c("Summary index", "Total")

kable(tab0, format = 'pandoc')

```

## {.tabset}
###2. Statistics by provinces
```{r detail, results='asis'}

tab1 <- ele %>%
  group_by(provinces, gender) %>%
  summarise(n_candidates=n()) %>%
  spread(gender, n_candidates) %>%
  arrange(provinces)
tab1$total <- tab1$female + tab1$male 

#female participation
tab1$fepa <- tab1$female/tab1$total*100
tab1$fepa <- round(tab1$fepa, digits=2)

#tab1a <- pandoc.table(tab1, emphasize.rows = which(tab1$fepa==min(tab1$fepa)))

#names(tab1) <- c("Cities/Provinces", "Number of female candidates", "Number of male candidates", "Total", "Percentage of female candidates")

#kable(tab1, format='pandoc')
```

```{r UI, results='asis'}
# UI

input_provinces <- unique(tab1$provinces)
selectInput("provinces",
            label = "Chọn tỉnh:",
            choices = input_provinces)

re_tab1 <- reactive({
  tab1 <- tab1[tab1$provinces == input$provinces, ]
  names(tab1) <- c("Cities/Provinces", "Number of female candidates", "Number of male candidates", "Total", "Percentage of female candidates")
  tab1
})

DT::renderDataTable(
  {re_tab1()},
  class = "nowrap stripe hover",
  rownames = FALSE,
  options = list(ordering = FALSE,
                 scrollX = TRUE,
                 language = list(url = "//cdn.datatables.net/plug-ins/1.10.7/i18n/Vietnamese.json"))
)


```

## {.tabset}
###3. Candidates by gender
```{r plotdetail, results='asis'}
tab1a <- ele %>%
  group_by(provinces, gender) %>%
  summarise(n_candidates=n())

plot1 <- ggplot(tab1a) +
  geom_bar(aes(x=reorder(provinces, n_candidates), y=n_candidates, fill=gender), stat = "identity") +
           #width = 2, position = position_dodge(0.5)) +
  theme_minimal() +
  labs(y = "Number of candidates", x = element_blank()) +
  theme(axis.title.y = element_text(size = 8)) +
  theme(axis.text.x = element_text(angle = 75, hjust=1, face = "italic", size = 4)) +
  theme(axis.text.y = element_text(size = 5)) +
  guides(fill=guide_legend(title = NULL)) +
  theme(panel.grid.minor.x = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          panel.grid.major.y = element_line(color = "gray90")) +
  scale_fill_manual(values = c("lightcoral", "lightblue3")) +
  scale_y_continuous(breaks = seq(0, 50, by=5))

print(plot1)

```

## {.tabset}
###4. Voting result
```{r plotresult, results='asis'}
plot2 <- ggplot(ele) 
plot2 <- plot2 + geom_point(aes(x=candidates, y=percentage, colour=gender), shape=21)
plot2 <- plot2 + ggtitle("Result By Gender") + 
  labs(y = "%", x = "Each dot = One candidate") + 
  theme_minimal() +
  theme(axis.text.x = element_blank()) +
  guides(colour=guide_legend(title = NULL)) +
  scale_colour_manual(values = c("lightcoral", "lightblue3"))

print(plot2)

```



